// Posts
export const POSTS_SET_LIST = 'POSTS_SET_LIST';
export const POSTS_RESET_LIST = 'POSTS_RESET_LIST';
export const POSTS_SET_SINGLE = 'POSTS_SET_SINGLE';
export const POSTS_RESET_SINGLE = 'POSTS_RESET_SINGLE';
export const POSTS_RESET_FILTER = 'POSTS_RESET_FILTER';
export const POSTS_DELETE_SINGLE = 'POSTS_DELETE_SINGLE';
export const POSTS_SET_FILTER_FIELD = 'POSTS_SET_FILTER_FIELD';
export const POSTS_SET_FILTER_ACTIVE = 'POSTS_SET_FILTER_ACTIVE';
export const POSTS_SET_FILTER_RESULTS = 'POSTS_SET_FILTER_RESULTS';
export const POSTS_SET_LOADING_STATUS = 'POSTS_SET_LOADING_STATUS';

// Comments
export const COMMENTS_RESET = 'COMMENTS_RESET';
export const COMMENTS_SET_DATA = 'COMMENTS_SET_DATA';
export const COMMENTS_SET_LOADING_STATUS = 'COMMENTS_SET_LOADING_STATUS';

// Users
export const USERS_SET_LIST = 'USERS_SET_LIST';
export const USERS_SET_SINGLE = 'USERS_SET_SINGLE';
export const USERS_RESET_SINGLE = 'USERS_RESET_SINGLE';
export const USERS_SET_SINGLE_LOADING_STATUS = 'USERS_SET_SINGLE_LOADING_STATUS';

// Server Error
export const SERVER_ERROR_RESET = 'SERVER_ERROR_RESET';
export const SERVER_ERROR_SET_DATA = 'SERVER_ERROR_SET_DATA';
